// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG6_KRbJiFiZafsUZ6HWf_RQCJDmtMSyw',
    appId: '1:974562949244:android:a5254d7811f5aa43b6f1f9',
    messagingSenderId: '974562949244',
    projectId: 'glucocare-62eb2',
    storageBucket: 'glucocare-62eb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNGaXPzwjeP3BSVmmLibDitUpqyiPT9PA',
    appId: '1:974562949244:ios:c7334421eef2de6db6f1f9',
    messagingSenderId: '974562949244',
    projectId: 'glucocare-62eb2',
    storageBucket: 'glucocare-62eb2.firebasestorage.app',
    iosClientId:
        '974562949244-7r35mo346v16mnu800ijs15spmrnaten.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestAi',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMSq5jnfhYoVjRiE2M9P_nZZxz4hI4jac',
    appId: '1:974562949244:web:54c7e3b4dc3a9635b6f1f9',
    messagingSenderId: '974562949244',
    projectId: 'glucocare-62eb2',
    authDomain: 'glucocare-62eb2.firebaseapp.com',
    storageBucket: 'glucocare-62eb2.firebasestorage.app',
    measurementId: 'G-HD92NX4JNF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNGaXPzwjeP3BSVmmLibDitUpqyiPT9PA',
    appId: '1:974562949244:ios:c7334421eef2de6db6f1f9',
    messagingSenderId: '974562949244',
    projectId: 'glucocare-62eb2',
    storageBucket: 'glucocare-62eb2.firebasestorage.app',
    iosClientId:
        '974562949244-7r35mo346v16mnu800ijs15spmrnaten.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMSq5jnfhYoVjRiE2M9P_nZZxz4hI4jac',
    appId: '1:974562949244:web:580934d73a27f758b6f1f9',
    messagingSenderId: '974562949244',
    projectId: 'glucocare-62eb2',
    authDomain: 'glucocare-62eb2.firebaseapp.com',
    storageBucket: 'glucocare-62eb2.firebasestorage.app',
    measurementId: 'G-5KNBNWVC1B',
  );
}
